### ISSUE TITLE
Add Carthage support

### ISSUE THREAD

**Issue by patricks** [Limon-O-O/KingfisherExtension#2]
Please add carthage support to your library.

**Comment by Limon-O-O** [comment]
Sorry, I try many times, but failed.
I `carthage build --no-skip-current` successfully, but I open another project `carthage update` failed.
Can you pull a request?

**Comment by patricks** [comment]
I have created carthage support the #3 
Please check if the cocoapods are working.

**Comment by patricks** [comment]
And don't forget to tag a new release, this is required for carthage.

**Comment by Limon-O-O** [comment]
Thanks!!!
Now, I know the better way to create a framework :)
